trigger: none
pr: none

variables:
  ParserProject: 'tools/apiview/parsers/csharp-api-parser/CSharpAPIParser.csproj'
  ScriptDirectory: 'tools/apiview/parsers/ConvertTokensToTreeStructure/ConvertTokensToTreeStructure'
  NugetSecurityAnalysisWarningLevel: 'none'

stages:
  - stage: 'CSharpToTreeTokens'
    jobs:
      - job: 'Run'
        timeoutInMinutes: 360

        pool:
          vmImage: 'windows-latest'

        steps:
          - script: 'dotnet tool install --global --add-source https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-net/nuget/v3/index.json --version 1.0.0-dev.20240626.4 CSharpAPIParser'
            displayName: 'Install Parser'

          - script: 'dotnet build $(ScriptDirectory)'
            displayName: 'Build Migration Script'
            env:
              DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
              DOTNET_CLI_TELEMETRY_OPTOUT: 1
              DOTNET_MULTILEVEL_LOOKUP: 0

          - script: 'dotnet run'
            displayName: 'Run Migration Script'
            workingDirectory: $(ScriptDirectory)
            env:
              DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
              DOTNET_CLI_TELEMETRY_OPTOUT: 1
              DOTNET_MULTILEVEL_LOOKUP: 0
              BlobConnectionString: $(BlobConnectionString)
              CosmosConnectionString: $(CosmosConnectionString)
