trigger:
- master

jobs:
- job: 'Build'

  pool:
    vmImage: 'ubuntu-16.04'  

  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.6'
    inputs:
      versionSpec: 3.6

  - script: |
     pip install setuptools 
     pip install wheel twine readme-renderer[md]
    displayName: 'Prep Environment'

  - script: |
      cd $(Build.SourcesDirectory)/packages/python-packages/doc-warden/
      python setup.py bdist_wheel -d $(Build.ArtifactStagingDirectory)
      python setup.py sdist -d $(Build.ArtifactStagingDirectory) --format zip
    displayName: 'Build Package'

  - task: CopyFiles@2
    displayName: 'Copy scripts for github release'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/scripts'
      Contents: '*/verify_agent_os.py'
      TargetFolder: '$(Build.BinariesDirectory)/sdk-tools'
      OverWrite: true
      flattenFolders: true

  - powershell: 'Get-ChildItem'
    workingDirectory: '$(Build.BinariesDirectory)'
    displayName: 'Display Content of the Build Binary Directory'

  - powershell: 'Get-ChildItem'
    workingDirectory: '$(Build.BinariesDirectory)/sdk-tools'
    displayName: 'Display Content of Build Binaries/sdk-tools'

  - script: |
      twine check $(Build.ArtifactStagingDirectory)/*
    displayName: 'Verify Readme'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    condition: succeededOrFailed()

  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
    # ComponentGovernance is currently unable to run on pull requests of public projects. Running on non-PR
    # builds should be sufficient.
    condition: and(succeededOrFailed(), ne(variables['Build.Reason'], 'PullRequest'))
    displayName: 'Component Detection'

- job: 'Test'
  
  dependsOn: 'Build'

  pool:
    vmImage: 'ubuntu-16.04'  

  steps:

  - task: UsePythonVersion@0
    displayName: 'Use Python 3.6'
    inputs:
      versionSpec: 3.6

  - script: |
      pip install setuptools 
      pip install wheel twine readme-renderer[md]

      cd $(Build.SourcesDirectory)
      mkdir sdk-for-js
      mkdir sdk-for-python
      mkdir sdk-for-java
      mkdir sdk-for-net

      git clone https://github.com/Azure/azure-sdk-for-java.git sdk-for-java
      git clone https://github.com/Azure/azure-sdk-for-python.git sdk-for-python
      git clone https://github.com/Azure/azure-sdk-for-js.git sdk-for-js
      git clone https://github.com/Azure/azure-sdk-for-net.git sdk-for-net
    displayName: 'Setup Environment'

  - script: |
      pip install -e $(Build.SourcesDirectory)/packages/python-packages/doc-warden/
    displayName: 'Install doc-warden'

  - script: |
      ward scan -d $(Build.SourcesDirectory)/sdk-for-java  -c $(Build.SourcesDirectory)/sdk-for-java/eng/.docsettings.yml -o True
    displayName: 'Ensure Java Backwards Compat'

  - script: |
      ward scan -d $(Build.SourcesDirectory)/sdk-for-net  -c $(Build.SourcesDirectory)/sdk-for-net/eng/.docsettings.yml -o True
    displayName: 'Ensure .NET Backwards Compat'

  - script: |
      ward scan -d $(Build.SourcesDirectory)/sdk-for-python -o True
    displayName: 'Ensure Python Backwards Compat'

  - script: |
      ward scan -d $(Build.SourcesDirectory)/sdk-for-js -o True
    displayName: 'Ensure JS Backwards Compat'
