name: Playground Job

on:
  workflow_dispatch:

jobs:
  run-powershell-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run PowerShell script
        shell: pwsh
        run: |
            $esc = [char]27
            $green = "${esc}[32m"
            $reset = "${esc}[0m"

            Write-Host "Regular Log"
            Write-Host "${green} Logg Success ${reset}"
            Write-Host "Regular Log"
